# Generated by Django 5.0.2 on 2024-03-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_id',
            new_name='no_of_pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='number_of_pages',
        ),
        migrations.AlterField(
            model_name='book',
            name='author_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
